---
- hosts: all
  vars:
    - ruby_version: 2.3.1
    - ruby_version_patch: 0
    - database_name: chatarc_development
    - database_name_test: chatarc_test
    - database_user: chatarc
    - database_password: chatarc
  roles:
    - { role: common }
    - { role: ruby }
    - { role: postgresql }
    - { role: web }
