---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Upgrade ubuntu
  apt: upgrade=yes
  sudo: yes

- name: Install dependencies
  apt: pkg={{item}} state=latest
  sudo: yes
  with_items:
    - build-essential
    - software-properties-common
    - libssl-dev
    - libreadline6-dev
    - libyaml-dev
    - zlib1g-dev
    - git
    - qt5-default
    - libqt5webkit5-dev
    - gstreamer1.0-plugins-base
    - gstreamer1.0-tools
    - gstreamer1.0-x
