default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: chatarc
  password:

development:
  <<: *default
  database: chatarc_development

test:
  <<: *default
  database: chatarc_test
