default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
